//go:build darwin

// Code generated by MockGen. DO NOT EDIT.
// Source: shortcuts.go
//
// Generated by this command:
//
//	mockgen -source=shortcuts.go -destination=mocks/shortcuts.go -package=mocks -build_constraint=darwin
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortcutsRunner is a mock of ShortcutsRunner interface.
type MockShortcutsRunner struct {
	ctrl     *gomock.Controller
	recorder *MockShortcutsRunnerMockRecorder
	isgomock struct{}
}

// MockShortcutsRunnerMockRecorder is the mock recorder for MockShortcutsRunner.
type MockShortcutsRunnerMockRecorder struct {
	mock *MockShortcutsRunner
}

// NewMockShortcutsRunner creates a new mock instance.
func NewMockShortcutsRunner(ctrl *gomock.Controller) *MockShortcutsRunner {
	mock := &MockShortcutsRunner{ctrl: ctrl}
	mock.recorder = &MockShortcutsRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortcutsRunner) EXPECT() *MockShortcutsRunnerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockShortcutsRunner) List(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShortcutsRunnerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShortcutsRunner)(nil).List), ctx)
}

// Run mocks base method.
func (m *MockShortcutsRunner) Run(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockShortcutsRunnerMockRecorder) Run(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockShortcutsRunner)(nil).Run), ctx, name)
}
