// Code generated by MockGen. DO NOT EDIT.
// Source: supervisor.go
//
// Generated by this command:
//
//	mockgen -source=supervisor.go -destination=mocks/stopper.go -package=mocks
//

//go:build darwin

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStopper is a mock of Stopper interface.
type MockStopper struct {
	ctrl     *gomock.Controller
	recorder *MockStopperMockRecorder
	isgomock struct{}
}

// MockStopperMockRecorder is the mock recorder for MockStopper.
type MockStopperMockRecorder struct {
	mock *MockStopper
}

// NewMockStopper creates a new mock instance.
func NewMockStopper(ctrl *gomock.Controller) *MockStopper {
	mock := &MockStopper{ctrl: ctrl}
	mock.recorder = &MockStopperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStopper) EXPECT() *MockStopperMockRecorder {
	return m.recorder
}

// RequestStop mocks base method.
func (m *MockStopper) RequestStop(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestStop", reason)
}

// RequestStop indicates an expected call of RequestStop.
func (mr *MockStopperMockRecorder) RequestStop(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestStop", reflect.TypeOf((*MockStopper)(nil).RequestStop), reason)
}
