// Code generated by MockGen. DO NOT EDIT.
// Source: deeplink.go
//
// Generated by this command:
//
//	mockgen -source=deeplink.go -destination=mocks/deeplink.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeepLinker is a mock of DeepLinker interface.
type MockDeepLinker struct {
	ctrl     *gomock.Controller
	recorder *MockDeepLinkerMockRecorder
	isgomock struct{}
}

// MockDeepLinkerMockRecorder is the mock recorder for MockDeepLinker.
type MockDeepLinkerMockRecorder struct {
	mock *MockDeepLinker
}

// NewMockDeepLinker creates a new mock instance.
func NewMockDeepLinker(ctrl *gomock.Controller) *MockDeepLinker {
	mock := &MockDeepLinker{ctrl: ctrl}
	mock.recorder = &MockDeepLinkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeepLinker) EXPECT() *MockDeepLinkerMockRecorder {
	return m.recorder
}

// OpenAX mocks base method.
func (m *MockDeepLinker) OpenAX() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenAX")
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenAX indicates an expected call of OpenAX.
func (mr *MockDeepLinkerMockRecorder) OpenAX() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenAX", reflect.TypeOf((*MockDeepLinker)(nil).OpenAX))
}

// OpenIM mocks base method.
func (m *MockDeepLinker) OpenIM() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenIM")
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenIM indicates an expected call of OpenIM.
func (mr *MockDeepLinkerMockRecorder) OpenIM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenIM", reflect.TypeOf((*MockDeepLinker)(nil).OpenIM))
}

// MockexecRunner is a mock of execRunner interface.
type MockexecRunner struct {
	ctrl     *gomock.Controller
	recorder *MockexecRunnerMockRecorder
	isgomock struct{}
}

// MockexecRunnerMockRecorder is the mock recorder for MockexecRunner.
type MockexecRunnerMockRecorder struct {
	mock *MockexecRunner
}

// NewMockexecRunner creates a new mock instance.
func NewMockexecRunner(ctrl *gomock.Controller) *MockexecRunner {
	mock := &MockexecRunner{ctrl: ctrl}
	mock.recorder = &MockexecRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexecRunner) EXPECT() *MockexecRunnerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockexecRunner) Start(name string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Start", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockexecRunnerMockRecorder) Start(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockexecRunner)(nil).Start), varargs...)
}
