// Code generated by MockGen. DO NOT EDIT.
// Source: waitgrants.go
//
// Generated by this command:
//
//	mockgen -source=waitgrants.go -destination=mocks/waitgrants.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
	isgomock struct{}
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// IsAXTrusted mocks base method.
func (m *MockChecker) IsAXTrusted() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAXTrusted")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAXTrusted indicates an expected call of IsAXTrusted.
func (mr *MockCheckerMockRecorder) IsAXTrusted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAXTrusted", reflect.TypeOf((*MockChecker)(nil).IsAXTrusted))
}

// IsIMGranted mocks base method.
func (m *MockChecker) IsIMGranted() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIMGranted")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsIMGranted indicates an expected call of IsIMGranted.
func (mr *MockCheckerMockRecorder) IsIMGranted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIMGranted", reflect.TypeOf((*MockChecker)(nil).IsIMGranted))
}
