// Code generated by MockGen. DO NOT EDIT.
// Source: orphan.go
//
// Generated by this command:
//
//	mockgen -source=orphan.go -destination=mocks/orphan.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	powerassert "github.com/dsbasko/dndmode/internal/macos/powerassert"
	gomock "go.uber.org/mock/gomock"
)

// MockAssertionEnumerator is a mock of AssertionEnumerator interface.
type MockAssertionEnumerator struct {
	ctrl     *gomock.Controller
	recorder *MockAssertionEnumeratorMockRecorder
	isgomock struct{}
}

// MockAssertionEnumeratorMockRecorder is the mock recorder for MockAssertionEnumerator.
type MockAssertionEnumeratorMockRecorder struct {
	mock *MockAssertionEnumerator
}

// NewMockAssertionEnumerator creates a new mock instance.
func NewMockAssertionEnumerator(ctrl *gomock.Controller) *MockAssertionEnumerator {
	mock := &MockAssertionEnumerator{ctrl: ctrl}
	mock.recorder = &MockAssertionEnumeratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssertionEnumerator) EXPECT() *MockAssertionEnumeratorMockRecorder {
	return m.recorder
}

// Enumerate mocks base method.
func (m *MockAssertionEnumerator) Enumerate(wantName, wantType string, ownPID int) ([]powerassert.Orphan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enumerate", wantName, wantType, ownPID)
	ret0, _ := ret[0].([]powerassert.Orphan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enumerate indicates an expected call of Enumerate.
func (mr *MockAssertionEnumeratorMockRecorder) Enumerate(wantName, wantType, ownPID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enumerate", reflect.TypeOf((*MockAssertionEnumerator)(nil).Enumerate), wantName, wantType, ownPID)
}

// MockAssertionReleaser is a mock of AssertionReleaser interface.
type MockAssertionReleaser struct {
	ctrl     *gomock.Controller
	recorder *MockAssertionReleaserMockRecorder
	isgomock struct{}
}

// MockAssertionReleaserMockRecorder is the mock recorder for MockAssertionReleaser.
type MockAssertionReleaserMockRecorder struct {
	mock *MockAssertionReleaser
}

// NewMockAssertionReleaser creates a new mock instance.
func NewMockAssertionReleaser(ctrl *gomock.Controller) *MockAssertionReleaser {
	mock := &MockAssertionReleaser{ctrl: ctrl}
	mock.recorder = &MockAssertionReleaserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssertionReleaser) EXPECT() *MockAssertionReleaserMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockAssertionReleaser) Release(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockAssertionReleaserMockRecorder) Release(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAssertionReleaser)(nil).Release), id)
}

// MockLiveChecker is a mock of LiveChecker interface.
type MockLiveChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLiveCheckerMockRecorder
	isgomock struct{}
}

// MockLiveCheckerMockRecorder is the mock recorder for MockLiveChecker.
type MockLiveCheckerMockRecorder struct {
	mock *MockLiveChecker
}

// NewMockLiveChecker creates a new mock instance.
func NewMockLiveChecker(ctrl *gomock.Controller) *MockLiveChecker {
	mock := &MockLiveChecker{ctrl: ctrl}
	mock.recorder = &MockLiveCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveChecker) EXPECT() *MockLiveCheckerMockRecorder {
	return m.recorder
}

// IsAlive mocks base method.
func (m *MockLiveChecker) IsAlive(pid int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAlive", pid)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAlive indicates an expected call of IsAlive.
func (mr *MockLiveCheckerMockRecorder) IsAlive(pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlive", reflect.TypeOf((*MockLiveChecker)(nil).IsAlive), pid)
}
