// Code generated by MockGen. DO NOT EDIT.
// Source: releaser.go
//
// Generated by this command:
//
//	mockgen -source=releaser.go -destination=mocks/releaser.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReleaser is a mock of Releaser interface.
type MockReleaser struct {
	ctrl     *gomock.Controller
	recorder *MockReleaserMockRecorder
	isgomock struct{}
}

// MockReleaserMockRecorder is the mock recorder for MockReleaser.
type MockReleaserMockRecorder struct {
	mock *MockReleaser
}

// NewMockReleaser creates a new mock instance.
func NewMockReleaser(ctrl *gomock.Controller) *MockReleaser {
	mock := &MockReleaser{ctrl: ctrl}
	mock.recorder = &MockReleaserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaser) EXPECT() *MockReleaserMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockReleaser) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockReleaserMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockReleaser)(nil).Name))
}

// Release mocks base method.
func (m *MockReleaser) Release() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockReleaserMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockReleaser)(nil).Release))
}
