//go:build darwin

// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mocks/runner.go -package=mocks -build_constraint=darwin
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVolumeRunner is a mock of VolumeRunner interface.
type MockVolumeRunner struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeRunnerMockRecorder
	isgomock struct{}
}

// MockVolumeRunnerMockRecorder is the mock recorder for MockVolumeRunner.
type MockVolumeRunnerMockRecorder struct {
	mock *MockVolumeRunner
}

// NewMockVolumeRunner creates a new mock instance.
func NewMockVolumeRunner(ctrl *gomock.Controller) *MockVolumeRunner {
	mock := &MockVolumeRunner{ctrl: ctrl}
	mock.recorder = &MockVolumeRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeRunner) EXPECT() *MockVolumeRunnerMockRecorder {
	return m.recorder
}

// GetMuted mocks base method.
func (m *MockVolumeRunner) GetMuted(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMuted", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMuted indicates an expected call of GetMuted.
func (mr *MockVolumeRunnerMockRecorder) GetMuted(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMuted", reflect.TypeOf((*MockVolumeRunner)(nil).GetMuted), ctx)
}

// SetMuted mocks base method.
func (m *MockVolumeRunner) SetMuted(ctx context.Context, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMuted", ctx, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMuted indicates an expected call of SetMuted.
func (mr *MockVolumeRunnerMockRecorder) SetMuted(ctx, muted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMuted", reflect.TypeOf((*MockVolumeRunner)(nil).SetMuted), ctx, muted)
}
